# ml_engine/models/relationship_training_data.py

train_texts = [
    # Parent-Child (0)
    "Happy birthday to my sweet daughter!",
    "Wishing my son a very happy birthday today.",
    "My mom deserves the best birthday ever.",
    "Happy birthday dad, love you so much.",
    "To my amazing child, happy birthday!",
    "Happy birthday to the best mother.",
    "Celebrating my father's birthday today.",
    "Happy birthday, my precious son.",
    "My daughter turns a year older today!",
    "Happy birthday to my wonderful child.",
    "Happy birthday, mom, you’re my hero.",
    "Dad, wishing you a birthday full of joy.",
    "Happy birthday to my lovely daughter.",
    "My son makes every birthday special.",
    "Mom, you deserve a fabulous birthday.",
    "Happy birthday, dad, stay blessed.",
    "Wishing my child a birthday full of fun.",
    "Happy birthday to my caring mother.",
    "Happy birthday to my supportive dad.",
    "Celebrating my child’s birthday today.",
    "Happy birthday to my awesome son.",
    "My daughter’s birthday is my favorite day.",
    "Mom, happy birthday and lots of love.",
    "Happy birthday, dad, you’re the best.",
    "My child is growing up so fast. Happy birthday!",
    "Happy birthday to the world's best mom.",
    "Happy birthday to the world’s best dad.",
    "My son deserves a grand birthday party.",
    "My daughter lights up her birthday cake.",
    "Happy birthday to my beloved child.",

    # Romantic-Partners (1)
    "Happy birthday to my loving wife.",
    "Wishing my husband a perfect birthday.",
    "Happy birthday sweetheart, I love you.",
    "To my boyfriend, happy birthday darling.",
    "My girlfriend deserves an amazing birthday.",
    "Happy birthday, my love and my life.",
    "Celebrating my partner’s birthday tonight.",
    "Happy birthday to my other half.",
    "Happy birthday my dearest fiancé.",
    "My husband makes every birthday magical.",
    "Happy birthday, my beautiful wife.",
    "Girlfriend, you’re my birthday wish come true.",
    "Happy birthday to my handsome boyfriend.",
    "Happy birthday to my soulmate.",
    "My partner deserves the best birthday ever.",
    "Wishing my love a fabulous birthday.",
    "Happy birthday to my gorgeous wife.",
    "Happy birthday to my loving partner.",
    "My boyfriend’s birthday makes me so happy.",
    "Happy birthday to my caring husband.",
    "Wishing my girlfriend pure joy on her birthday.",
    "Happy birthday to my sweet boyfriend.",
    "My partner’s birthday is my favorite day.",
    "Wishing my fiancé a happy birthday full of love.",
    "Happy birthday, babe. You mean everything.",
    "My partner’s birthday calls for a celebration.",
    "Happy birthday to the love of my life.",
    "Girlfriend, I hope your birthday is amazing.",
    "Happy birthday, darling. I adore you.",
    "Wishing my spouse a beautiful birthday.",

    # Friends (2)
    "Happy birthday to my best friend!",
    "Wishing my buddy a fantastic birthday.",
    "Bestie, happy birthday and lots of love.",
    "Happy birthday to my childhood friend.",
    "Happy birthday to my college roommate.",
    "My friend deserves an epic birthday party.",
    "Happy birthday to my partner in crime.",
    "Cheers to my friend’s birthday tonight.",
    "My friend always makes birthdays fun.",
    "Happy birthday, my dear friend.",
    "Celebrating my friend’s birthday today.",
    "Happy birthday, you crazy friend!",
    "My buddy gets the coolest gifts on birthdays.",
    "Happy birthday to my closest friend.",
    "Wishing my friend a joyful birthday.",
    "Happy birthday, friend, you’re the best.",
    "My friend’s birthday is a special day.",
    "Bestie deserves an amazing birthday.",
    "Happy birthday to my loyal friend.",
    "My friend makes birthdays unforgettable.",
    "Happy birthday, friend, let’s party!",
    "My friend’s birthday brings us together.",
    "Happy birthday, friend, you rock!",
    "Wishing my friend a day of laughter.",
    "Happy birthday to my funny friend.",
    "My friend’s birthday means cake and fun.",
    "Happy birthday, friend, stay awesome.",
    "My friend deserves birthday hugs.",
    "Cheers to another year, friend. Happy birthday!",
    "My friend’s birthday is always a blast.",

    # Siblings (3)
    "Happy birthday to my brother!",
    "Wishing my sister a fabulous birthday.",
    "Happy birthday, my dear sibling.",
    "Happy birthday to my little brother.",
    "Happy birthday, big sister, love you.",
    "My brother makes birthdays amazing.",
    "Happy birthday to my caring sister.",
    "Celebrating my brother’s birthday today.",
    "My sister deserves the best birthday.",
    "Happy birthday, sibling, stay awesome.",
    "Happy birthday to my twin brother.",
    "My sister and I share birthday memories.",
    "Happy birthday to my goofy brother.",
    "My brother makes every birthday fun.",
    "Happy birthday to my sweet sister.",
    "Happy birthday, brother, you rock!",
    "Wishing my sister joy on her birthday.",
    "Happy birthday, brother, party time!",
    "My sister’s birthday calls for cake.",
    "Happy birthday, sibling, you’re the best.",
    "My brother’s birthday is my favorite day.",
    "My sister lights up her birthday cake.",
    "Happy birthday, brother, stay cool.",
    "Happy birthday, sister, you’re amazing.",
    "My sibling deserves a grand birthday.",
    "Happy birthday, sister, hugs and kisses.",
    "Happy birthday, brother, let’s celebrate.",
    "Happy birthday, sister, love you tons.",
    "Brother, wishing you the best birthday.",
    "Sister, happy birthday, my confidant.",

    # Professional (4)
    "Happy birthday to my boss!",
    "Wishing my colleague a great birthday.",
    "Happy birthday to our amazing manager.",
    "My coworker deserves a fabulous birthday.",
    "Celebrating my teammate’s birthday today.",
    "Happy birthday to my office buddy.",
    "Wishing my supervisor a happy birthday.",
    "My colleague’s birthday calls for cake.",
    "Happy birthday to my coworker.",
    "Wishing our director a joyful birthday.",
    "Happy birthday to my work friend.",
    "My boss deserves a great birthday party.",
    "Happy birthday, colleague, enjoy your day.",
    "My team is celebrating a birthday today.",
    "Happy birthday to my professional mentor.",
    "Wishing my coworker lots of birthday fun.",
    "Happy birthday, boss, thanks for everything.",
    "Wishing my manager a wonderful birthday.",
    "Happy birthday to our project lead.",
    "Happy birthday to my coworker in HR.",
    "Happy birthday to my team leader.",
    "My office celebrates birthdays in style.",
    "Happy birthday to the CEO today.",
    "Happy birthday to my reliable coworker.",
    "My coworker gets birthday donuts today.",
    "Wishing my boss a peaceful birthday.",
    "Happy birthday, manager, we appreciate you.",
    "Wishing my colleague a birthday full of joy.",
    "Happy birthday, coworker, have fun.",
    "My coworker deserves the best birthday.",

    # Myself (5)
    "Happy birthday to me!",
    "Treating myself on my birthday.",
    "Today is my special birthday.",
    "I’m grateful for another birthday.",
    "Celebrating my birthday alone today.",
    "I bought myself a cake for my birthday.",
    "I’m pampering myself this birthday.",
    "My birthday is my day to shine.",
    "Reflecting on my life this birthday.",
    "I’m making birthday wishes for myself.",
    "I’m planning my own birthday party.",
    "My birthday means new beginnings.",
    "Enjoying my solo birthday celebration.",
    "Taking the day off for my birthday.",
    "I deserve a fabulous birthday today.",
    "I’m buying gifts for myself this birthday.",
    "Happy birthday to me, feeling grateful.",
    "I’m dancing alone for my birthday.",
    "My birthday is a quiet day this year.",
    "Treating myself to a spa day birthday.",
    "I’m my own birthday hero today.",
    "I’m feeling blessed on my birthday.",
    "I’m smiling big on my birthday.",
    "My birthday is full of self-love.",
    "My birthday is my personal holiday.",
    "I’m journaling about my birthday wishes.",
    "Enjoying a peaceful birthday alone.",
    "I’m thankful for my birthday blessings.",
    "Singing happy birthday to myself.",
    "I’m loving myself extra this birthday.",
]

# Build corresponding labels
train_labels = []

# Append 30 labels per class
for label in range(6):
    train_labels += [label] * 30
